version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/frontend
    ports:
      - 3333:3000
    image: app:pexel-react
    container_name: react_pexel_container
    command: npm start
