# Generated by Django 3.2.9 on 2021-11-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='videosId',
            new_name='videoId',
        ),
        migrations.AlterUniqueTogether(
            name='videos',
            unique_together={('user', 'videoId')},
        ),
    ]
